# typed: false
# frozen_string_literal: true

# Auto-generated by WAGENT publish script. DO NOT EDIT.
class Wagent < Formula
  desc "WhatsApp AI Agent Platform - Multi-provider, self-hosted"
  homepage "https://github.com/crediblemark-official/WAGENT"
  version "0.2.0"
  license "MIT"

  depends_on "node" => :recommended

  def install
    # Install via npm global
    system "npm", "install", "-g", "wagent@#{version}"
    
    # Also install the bin wrapper
    bin.install "wagent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wagent --version")
  end
end
